package it.polimi.ingsw.network.message.connectionmessage;

public enum ConnectionMessageType {
    CREATE_GAME_REQUEST, JOIN_GAME_REQUEST, LOBBY_LIST_REQUEST, LOBBY_LIST_RESPONSE, CREATE_LOBBY_REQUEST, CREATE_LOBBY_RESPONSE, JOIN_LOBBY_REQUEST, JOIN_LOBBY_RESPONSE, LOGIN_REQUEST, USERNAME_REQUEST, USERNAME_RESPONSE, LOGIN_RESPONSE, RECONNECTION, CONNECTED_TO_SERVER

}
