package it.polimi.ingsw.network.message.lobbymessage;

public enum LobbyMessageType {
    START_GAME_REQUEST, EXIT_LOBBY_RESPONSE, PLAYERS_UPDATE, GAME_NOT_READY, NEW_ADMIN, NOT_ADMIN, CHANGE_NUM_OF_PLAYER_REQUEST, INVALID_COMMAND, CHANGE_NUM_OF_PLAYER_RESPONSE, EXIT_LOBBY_REQUEST

}
